image: ruby:2.5

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

stages:
  - installation
  - structuring
  - generation
  - test
  - deploy

api_data:
  stage: installation
  script:
  - scripts/get-api-data.sh | bash

gems:
  stage: installation
  script:
  - gem install bundler
  - bundle update

npm:
  stage: installation
  script:
  - apt-get update -y
  - apt-get install -y curl
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash
  - source /root/.bashrc
  - nvm install node
  - nvm use node
  - npm install
  artifacts:
    paths:
    - node_modules

sass:
  stage: generation
  script: 
  - scripts/compile-sass.sh | bash

structure:
  stage: structuring
  script: 
  - scripts/structurize.sh | bash

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master