image: ruby:2.5

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - apt-get update -y
  - apt-get install -y curl
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash
  - source /root/.bashrc
  - nvm install node
  - nvm use node
  - npm install
  - gem install bundler jekyll
  - bundle install
  - ls
  - cd scripts
  - chmod +x get-api-data.sh
  - ls
  - cd ..
  - ls
  - chmod +x scripts/structurize.sh
  - ls
  - chmod +x scripts/compile-sass.sh
  - ls

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master