image: ruby:2.5

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - apt-get update -y
  - apt-get install -y libssl-dev build-essential wget
  - wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.29.0/install.sh | bash
  - source /root/.bashrc
  - nvm install 6.6.0
  - nvm use 6.6.0
  - node -v
  - npm -v
  - npm install
  - gem install bundler
  - bundle install
  - move /Y node_modules/bootstrap assets/
  - move node_modules/jquery assets/
  - move /Y node_modules/popper.js assets/
  - rmdir node_modules
  - sass assets/scss/theme.scss assets/css/theme.css
  
test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master
