image: ruby:2.5

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - apt-get update -y
  - apt-get install -y curl
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash
  - source /root/.bashrc
  - nvm install node
  - nvm use node
  - npm install
  - gem install bundler jekyll
  - bundle install
  - mkdir ./_data/api_fetch
  - curl -o- https://gitlab.gnome.org/api/v4/projects/665/repository/tags?order_by=name > ./_data/api_fetch/tags.json
  - curl -o- https://api.rss2json.com/v1/api.json?rss_url=https%3A%2F%2Fblog.gtk.org%2Ffeed%2F > ./_data/api_fetch/gtk-blog-feed.json
  - curl -o- https://gitlab.gnome.org/api/v4/projects/665/issues_statistics > ./_data/api_fetch/issues_stats.json
  - curl -o- https://gitlab.gnome.org/api/v4/projects/665/issues?state=opened > ./_data/api_fetch/tags.json
  - mv ./node_modules/* ./assets/ -f
  - rm -rf ../node_modules
  - sass assets/scss/theme.scss assets/css/theme.css

test:
  stage: test
  script:
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master