name: The GTK Project
title: The GTK Project | A free and open-source cross-platform widget toolkit
description: GTK is a highly usable, feature rich toolkit for creating graphical user interfaces which boasts cross platform compatibility and an easy to use API. GTK is licensed under the GNU LGPL 2.1 allowing development of both free and proprietary software with GTK without any license fees or royalties.
baseurl: ''
url: 'https://ravgeetdhillon.pages.gitlab.gnome.org/gtk-web/'
markdown: kramdown
kramdown: 
  parse_block_html: true
  input: GFM
highlighter: rouge
# plugins:
#   - jekyll-feed
# sass:
#   sass_dir: _sass
# include:
#   - .htaccess
exclude: 
  - documents/
  - node_modules/
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - community.html
  - README.md
  - CONTRIBUTING.md
# for dev only
# keep_files: [assets]

collections_dir: collections

collections:
  docs:
    output: true

defaults:
  - scope:
      type: docs
    values:
      layout: documentation
      navbar_dark: true